# Generated by Django 5.2.4 on 2025-07-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('closing_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_postings', to=settings.AUTH_USER_MODEL)),
                ('customer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='companies.customercompany')),
                ('hr_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='companies.hrcompany')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
