# Generated by Django 5.2.4 on 2025-08-01 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_customercompany_companies_c_code_071934_idx_and_more'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['hr_company'], name='jobs_jobpos_hr_comp_5eea1e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['customer_company'], name='jobs_jobpos_custome_244f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status'], name='jobs_jobpos_status_99cc43_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active'], name='jobs_jobpos_is_acti_6314b1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['created_by'], name='jobs_jobpos_created_b8bc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['created_at'], name='jobs_jobpos_created_d079a9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['closing_date'], name='jobs_jobpos_closing_383f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['hr_company', 'customer_company'], name='jobs_jobpos_hr_comp_5e883f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', 'is_active'], name='jobs_jobpos_status_97988c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['hr_company', 'is_active'], name='jobs_jobpos_hr_comp_9c040c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['-created_at'], name='jobs_jobpos_created_ba4c9f_idx'),
        ),
    ]
