# Generated by Django 5.2.4 on 2025-07-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('companies', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_flows', to='candidates.candidate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_candidate_flows', to=settings.AUTH_USER_MODEL)),
                ('hr_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_flows', to='companies.hrcompany')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_flows', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job_posting', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='flows.activitytype')),
            ],
            options={
                'unique_together': {('name', 'activity_type')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('hr_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.hrcompany')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='flows.activitytype')),
                ('candidate_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='flows.candidateflow')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='flows.status')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
