# Generated by Django 5.2.4 on 2025-08-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['activity_type__name', 'name']},
        ),
    ]
