# Generated by Django 5.2.4 on 2025-08-01 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_candidates__email_188e48_idx_and_more'),
        ('companies', '0002_customercompany_companies_c_code_071934_idx_and_more'),
        ('flows', '0002_alter_activitytype_options_alter_status_options'),
        ('jobs', '0002_jobposting_jobs_jobpos_hr_comp_5eea1e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['candidate_flow'], name='flows_activ_candida_1cd543_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='flows_activ_activit_26bdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='flows_activ_status__70f620_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_by'], name='flows_activ_created_83b428_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['hr_company'], name='flows_activ_hr_comp_eeb519_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_at'], name='flows_activ_created_fc5e78_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['candidate_flow', 'activity_type'], name='flows_activ_candida_4c43d1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['hr_company', 'created_by'], name='flows_activ_hr_comp_a9f21f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-created_at'], name='flows_activ_created_d5583e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['job_posting'], name='flows_candi_job_pos_b26413_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['candidate'], name='flows_candi_candida_acbadb_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['hr_company'], name='flows_candi_hr_comp_65037a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['created_by'], name='flows_candi_created_5a0a64_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['flow_status'], name='flows_candi_flow_st_f1c13f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['is_active'], name='flows_candi_is_acti_3cef44_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['created_at'], name='flows_candi_created_7c7835_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['hr_company', 'flow_status'], name='flows_candi_hr_comp_776dca_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['flow_status', 'is_active'], name='flows_candi_flow_st_9d926b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['hr_company', 'is_active'], name='flows_candi_hr_comp_e1e791_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['job_posting', 'candidate'], name='flows_candi_job_pos_b22d52_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateflow',
            index=models.Index(fields=['-created_at'], name='flows_candi_created_f1a2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['activity_type'], name='flows_statu_activit_2031f9_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['is_active'], name='flows_statu_is_acti_ac0c87_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['created_at'], name='flows_statu_created_e058a6_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['activity_type', 'is_active'], name='flows_statu_activit_1bff2e_idx'),
        ),
    ]
