# Generated by Django 5.2.4 on 2025-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hruser_hr_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
