# Generated by Django 5.2.4 on 2025-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_hruser_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0002_customercompany_companies_c_code_071934_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hruser',
            options={},
        ),
        migrations.AddIndex(
            model_name='hruser',
            index=models.Index(fields=['email'], name='accounts_hr_email_9cb222_idx'),
        ),
        migrations.AddIndex(
            model_name='hruser',
            index=models.Index(fields=['hr_company'], name='accounts_hr_hr_comp_2f6b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='hruser',
            index=models.Index(fields=['is_active'], name='accounts_hr_is_acti_b8a7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='hruser',
            index=models.Index(fields=['created_at'], name='accounts_hr_created_44bf73_idx'),
        ),
        migrations.AddIndex(
            model_name='hruser',
            index=models.Index(fields=['hr_company', 'is_active'], name='accounts_hr_hr_comp_19429d_idx'),
        ),
        migrations.AddIndex(
            model_name='hruser',
            index=models.Index(fields=['-created_at'], name='accounts_hr_created_6a239e_idx'),
        ),
    ]
