# Generated by Django 5.2.4 on 2025-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='candidates__email_188e48_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['is_active'], name='candidates__is_acti_c99c44_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_at'], name='candidates__created_a71da5_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['first_name'], name='candidates__first_n_4c86b1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['last_name'], name='candidates__last_na_381a88_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['phone'], name='candidates__phone_436030_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['first_name', 'last_name'], name='candidates__first_n_49b5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='candidates__created_d94c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['candidate'], name='candidates__candida_871343_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['start_date'], name='candidates__start_d_1b7083_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['end_date'], name='candidates__end_dat_4c4698_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['is_current'], name='candidates__is_curr_3fe5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['school_name'], name='candidates__school__71cc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['candidate', 'start_date'], name='candidates__candida_2745a9_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['-start_date'], name='candidates__start_d_84750e_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['candidate'], name='candidates__candida_a984a1_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['start_date'], name='candidates__start_d_7ef213_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['end_date'], name='candidates__end_dat_72f509_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['is_current'], name='candidates__is_curr_646cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['company_name'], name='candidates__company_a75e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['candidate', 'start_date'], name='candidates__candida_4144dc_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['-start_date'], name='candidates__start_d_23e607_idx'),
        ),
    ]
