# Generated by Django 5.2.4 on 2025-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['start_date'], name='reports_rep_start_d_c9cca1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['end_date'], name='reports_rep_end_dat_90a626_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_at'], name='reports_rep_generat_35ba4e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['completed_at'], name='reports_rep_complet_a6e8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-generated_at'], name='reports_rep_generat_fa1e6b_idx'),
        ),
    ]
