# Generated by Django 5.2.4 on 2025-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customercompany',
            index=models.Index(fields=['code'], name='companies_c_code_071934_idx'),
        ),
        migrations.AddIndex(
            model_name='customercompany',
            index=models.Index(fields=['is_active'], name='companies_c_is_acti_22a541_idx'),
        ),
        migrations.AddIndex(
            model_name='customercompany',
            index=models.Index(fields=['created_at'], name='companies_c_created_39ee71_idx'),
        ),
        migrations.AddIndex(
            model_name='customercompany',
            index=models.Index(fields=['name'], name='companies_c_name_1b74b2_idx'),
        ),
        migrations.AddIndex(
            model_name='customercompany',
            index=models.Index(fields=['-created_at'], name='companies_c_created_db2a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcompany',
            index=models.Index(fields=['code'], name='companies_h_code_3d4f18_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcompany',
            index=models.Index(fields=['is_active'], name='companies_h_is_acti_1b6a41_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcompany',
            index=models.Index(fields=['created_at'], name='companies_h_created_99842c_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcompany',
            index=models.Index(fields=['name'], name='companies_h_name_104ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcompany',
            index=models.Index(fields=['-created_at'], name='companies_h_created_a455bb_idx'),
        ),
    ]
